{% set name = "llvmlite" %}
{% set version = "0.47.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/numba/llvmlite/archive/refs/heads/release0.47.tar.gz
  sha256: 3391cd925dbcdd5d0425a626d27e0537c486722ba974d128111ead64e4043df1

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake <4
    - make                   # [unix]
  host:
    - python
    - setuptools
    - llvmdev 20.*.*        # abstract pin for static lib
    - llvmdev 20.1.8 *_0    # concrete pin for static lib - bot should update
    - zlib
    - zstd
  run:
    - python

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - jakirkham
    - souravsingh
    - marcelotrevisani
    - xhochy
    - mbargull
    - beckermr
    - esc
